export const mockData = [{
    "index": "0",
    "bathroom_number":"",
    "bedroom_number":3,
    "car_spaces":0,
    "commission":0,
    "construction_year":0,
    "datasource_name":"OnTheMarket.com",
    "img_height":300,
    "img_url":"https://imgs.nestimg.com/3_bedroom_detached_house_for_sale_111946676250550550.jpg",
    "img_width":400,
    "keywords":"Detached",
    "latitude":51.694515,
    "lister_url":"https://www.nestoria.co.uk/detail/0000000111946676250550550/title/5/1-1?serpUid=&pt=1&ot=1&l=godreaman&did=105_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
    "listing_type":"buy",
    "location_accuracy":9,
    "longitude":-3.4299147,
    "price":399950,
    "price_currency":"£",
    "price_formatted":"£399,950",
    "price_high":399950,
    "price_low":399950,
    "price_type":"fixed",
    "property_type":"house",
    "size":0,
    "size_type":"net",
    "summary":"Opportunity to be appointed as the local selling agent for the parc...",
    "thumb_height":60,
    "thumb_url":"https://imgs.nestimg.com/medium/3_bedroom_detached_house_for_sale_111946676250550550.jpg",
    "thumb_width":80,
    "title":"Parc Cynefin, Godreaman, Aberdare",
    "updated_in_days":4,
    "updated_in_days_formatted":"first seen 4 days ago"
    },
    {
    "index": "1",
    "bathroom_number":"",
    "bedroom_number":3,
    "car_spaces":0,
    "commission":0,
    "construction_year":0,
    "datasource_name":"Home.co.uk",
    "img_height":300,
    "img_url":"https://resources.nestimg.com/nestoria/img/noimage/desktop/house/2.png",
    "img_width":400,
    "keywords":"Garden, Terraced, Kitchen, Basement",
    "latitude":51.666218,
    "lister_name":"Darlows",
    "lister_url":"https://www.nestoria.co.uk/detail/0000000110586006961471282/title/5/1-2?serpUid=&pt=1&ot=1&l=godreaman&did=85_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
    "listing_type":"buy",
    "location_accuracy":10,
    "longitude":-3.448092,
    "price":69999,
    "price_currency":"£",
    "price_formatted":"£69,999",
    "price_high":69999,
    "price_low":69999,
    "price_type":"fixed",
    "property_type":"house",
    "size":0,
    "size_type":"net",
    "summary":"Mid terraced, three storey property offering good accommodation for...",
    "thumb_height":60,
    "thumb_url":"https://resources.nestimg.com/nestoria/img/noimage/mobile/house/2.png",
    "thumb_width":80,
    "title":"Taff Street, Blaenllechau - Garden",
    "updated_in_days":32,
    "updated_in_days_formatted":"first seen over a month ago"
}]